[package]
name = "box_stream"
version = "0.2.1"
authors = ["AljoschaMeyer <mail@aljoscha-meyer.de>"]
description = "Implementation of the box-stream encryption protocol."
repository = "https://github.com/AljoschaMeyer/box-stream-rs"
readme = "README.md"
license = "GPL-3.0"

[dependencies]
libc = "0.2"
libsodium-sys = "0.0.15"
sodiumoxide = "0.0.15"
rand = "0.3"
tokio-io = "0.1.2"
futures = "0.1.14"

[build-dependencies]
gcc = "0.3"
